### ISSUE TITLE
[Feature Request]Implement Purpur patches

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Mirai#11]
Purpur contains patches from Pufferfish and more customizable, hope Mirai getting better❤

**Comment by Dreeam-qwq** [comment]
You can see MiraiPurpur branch, including Mirai and Purpur
https://github.com/Dreeam-qwq/Mirai/tree/purpur/1.20.1
and the releases of it https://github.com/Dreeam-qwq/Mirai/releases/tag/purpur-1.20.1

**Comment by HaHaWTH** [comment]
Got it, thx so much❤
