### ISSUE TITLE
[建议] 能不能采用LeavesMC的paper

### ISSUE THREAD

**Issue by safesaffawa** [Dreeam-qwq/Mirai#9]
https://github.com/LeavesMC/Leaves
LeavesMC 为paper修复了许多不生电的内容
希望作者能为了做一个1.20 
基于这个版本的paper mirai
如果做出来了 非常感谢作者
抽空制作这个版本的paper mirai
谢谢uwu
 
--既然是国人就说中文了

**Comment by s-yh-china** [comment]
hhhhhhh

**Comment by Dreeam-qwq** [comment]
已完成
https://github.com/Dreeam-qwq/Mirai/releases/tag/leaves-1.20.1

此分支不会进行后续更新/维护(大概)
如有Leaves的优化需求，可向Leaves提出相关需求。另外Leaves本身已经包含了pufferfish和gale核心的优化
